import fs from "fs";
import path from "path";
import pc from "picocolors";
import { globSync } from "tinyglobby";
import { verifyLock } from "../codelock";
import { detectCommentSyntax } from "../detectCommentSyntax";

export type FileStatus =
  /** File is not generated by tscodegen. Skipped, but not a failure. */
  | "skipped"
  /** File is locked and the hash matches its contents. */
  | "ok"
  /** File has a codelock marker but the contents have been tampered with. */
  | "tampered"
  /** File was listed on the command line but could not be read. */
  | "error";

export interface FileResult {
  file: string;
  status: FileStatus;
  /** Populated for `error` statuses. */
  message?: string;
}

export interface VerifyOptions {
  /** Working directory used to resolve patterns. Defaults to `process.cwd()`. */
  cwd?: string;
  /** Additional glob patterns to exclude. */
  ignore?: readonly string[];
  /** Whether to include dotfiles when matching globs. Defaults to `true`. */
  dot?: boolean;
}

const DEFAULT_IGNORE = ["**/node_modules/**", "**/.git/**"];

/**
 * Verify a single file on disk. Returns the result without throwing — I/O and
 * parse errors are surfaced via {@link FileResult.status} === `"error"`.
 */
export function verifyFile(absolutePath: string, relPath: string): FileResult {
  let contents: string;
  try {
    contents = fs.readFileSync(absolutePath, "utf-8");
  } catch (err) {
    return {
      file: relPath,
      status: "error",
      message: err instanceof Error ? err.message : String(err),
    };
  }

  const syntax = detectCommentSyntax(contents);
  if (!syntax) {
    return { file: relPath, status: "skipped" };
  }

  return {
    file: relPath,
    status: verifyLock(contents, syntax) ? "ok" : "tampered",
  };
}

/**
 * Expand the supplied {@link patterns} into a sorted list of files, relative
 * to {@link VerifyOptions.cwd}. Literal (non-glob) paths are included verbatim
 * if they exist on disk, even when they would not normally be matched by the
 * glob engine (e.g. because they live outside the default ignore set).
 */
export function resolveFiles(
  patterns: readonly string[],
  options: VerifyOptions = {},
): string[] {
  const cwd = options.cwd ?? process.cwd();
  const ignore = [...DEFAULT_IGNORE, ...(options.ignore ?? [])];
  const dot = options.dot ?? true;

  const files = new Set<string>();

  const globPatterns: string[] = [];
  for (const pattern of patterns) {
    const absolute = path.resolve(cwd, pattern);
    let stat: fs.Stats | undefined;
    try {
      stat = fs.statSync(absolute);
    } catch {
      stat = undefined;
    }
    if (stat?.isFile()) {
      files.add(path.relative(cwd, absolute) || path.basename(absolute));
      continue;
    }
    if (stat?.isDirectory()) {
      globPatterns.push(path.posix.join(toPosix(pattern), "**/*"));
      continue;
    }
    globPatterns.push(toPosix(pattern));
  }

  if (globPatterns.length > 0) {
    const matched = globSync(globPatterns, {
      cwd,
      absolute: false,
      dot,
      onlyFiles: true,
      ignore,
    });
    for (const file of matched) {
      files.add(file);
    }
  }

  return [...files].sort();
}

function toPosix(p: string): string {
  return p.split(path.sep).join(path.posix.sep);
}

export interface VerifyRunResult {
  results: FileResult[];
  okCount: number;
  skippedCount: number;
  tamperedCount: number;
  errorCount: number;
  /**
   * Process exit code. `0` when no files were tampered with and no errors
   * occurred, `1` otherwise.
   */
  exitCode: number;
}

export interface RunOptions extends VerifyOptions {
  /** Stream used for informational output. Defaults to `process.stdout`. */
  stdout?: NodeJS.WritableStream;
  /** Stream used for errors. Defaults to `process.stderr`. */
  stderr?: NodeJS.WritableStream;
  /** Suppress per-file output; only print the summary and errors. */
  quiet?: boolean;
  /** Disable ANSI colors even if the stream is a TTY. */
  noColor?: boolean;
  /** Print every file's status, including skipped ones. */
  verbose?: boolean;
}

/**
 * Run the CLI with the given patterns and options. Intended to be called
 * directly from tests as well as from the `bin/verify-codelock.js` wrapper.
 */
export function run(
  patterns: readonly string[],
  options: RunOptions = {},
): VerifyRunResult {
  const stdout = options.stdout ?? process.stdout;
  const stderr = options.stderr ?? process.stderr;
  const cwd = options.cwd ?? process.cwd();
  const colors = options.noColor ? plainColors : pc;

  if (patterns.length === 0) {
    stderr.write(
      "verify-codelock: no patterns provided. Pass one or more glob patterns or file paths.\n",
    );
    return emptyResult(2);
  }

  const files = resolveFiles(patterns, {
    cwd,
    ignore: options.ignore,
    dot: options.dot,
  });

  if (files.length === 0) {
    stderr.write(
      `verify-codelock: no files matched the supplied patterns: ${patterns.join(", ")}\n`,
    );
    return emptyResult(1);
  }

  const results: FileResult[] = [];
  let okCount = 0;
  let skippedCount = 0;
  let tamperedCount = 0;
  let errorCount = 0;

  for (const file of files) {
    const absolute = path.resolve(cwd, file);
    const result = verifyFile(absolute, file);
    results.push(result);

    switch (result.status) {
      case "ok":
        okCount += 1;
        if (options.verbose && !options.quiet) {
          stdout.write(`${colors.green("ok")}       ${file}\n`);
        }
        break;
      case "skipped":
        skippedCount += 1;
        if (options.verbose && !options.quiet) {
          stdout.write(`${colors.dim("skipped")}  ${file}\n`);
        }
        break;
      case "tampered":
        tamperedCount += 1;
        if (!options.quiet) {
          stdout.write(`${colors.red("tampered")} ${file}\n`);
        }
        break;
      case "error":
        errorCount += 1;
        stderr.write(
          `${colors.red("error")}    ${file}: ${result.message ?? "unknown error"}\n`,
        );
        break;
    }
  }

  if (!options.quiet) {
    const parts = [
      `${colors.green(`${okCount} ok`)}`,
      `${colors.dim(`${skippedCount} skipped`)}`,
    ];
    if (tamperedCount > 0) {
      parts.push(colors.red(`${tamperedCount} tampered`));
    }
    if (errorCount > 0) {
      parts.push(
        colors.red(`${errorCount} error${errorCount === 1 ? "" : "s"}`),
      );
    }
    stdout.write(
      `\nverify-codelock: checked ${files.length} file${files.length === 1 ? "" : "s"} (${parts.join(", ")}).\n`,
    );

    if (tamperedCount > 0) {
      stderr.write(
        `\n${colors.red(
          "Some tscodegen-generated files have been modified outside their manual sections.",
        )}\nRe-run the codegen script that produced each file, or restore the file's previous contents.\n`,
      );
    }
  }

  const exitCode = tamperedCount > 0 || errorCount > 0 ? 1 : 0;
  return {
    results,
    okCount,
    skippedCount,
    tamperedCount,
    errorCount,
    exitCode,
  };
}

function emptyResult(exitCode: number): VerifyRunResult {
  return {
    results: [],
    okCount: 0,
    skippedCount: 0,
    tamperedCount: 0,
    errorCount: 0,
    exitCode,
  };
}

/** A `picocolors`-compatible no-op palette used when color output is disabled. */
const plainColors: {
  green: (s: string) => string;
  red: (s: string) => string;
  dim: (s: string) => string;
} = {
  green: (s) => s,
  red: (s) => s,
  dim: (s) => s,
};

export interface ParsedArgs {
  patterns: string[];
  ignore: string[];
  quiet: boolean;
  verbose: boolean;
  noColor: boolean;
  help: boolean;
  version: boolean;
  /**
   * Set if argument parsing failed. When set, callers should print the
   * message to stderr and exit with a non-zero status.
   */
  error?: string;
}

/**
 * Parse command-line arguments. Designed to mirror the shape of common
 * lint-style CLIs:
 *
 * ```
 * verify-codelock [options] <pattern> [<pattern>...]
 *   --ignore <pattern>    Exclude files matching <pattern>. May be repeated.
 *   --quiet               Suppress per-file output and the summary line.
 *   --verbose             Log the status of every file, including skipped ones.
 *   --no-color            Disable colored output.
 *   -h, --help            Print help and exit.
 *   -v, --version         Print the installed tscodegen version and exit.
 * ```
 */
export function parseArgs(argv: readonly string[]): ParsedArgs {
  const parsed: ParsedArgs = {
    patterns: [],
    ignore: [],
    quiet: false,
    verbose: false,
    noColor: false,
    help: false,
    version: false,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--") {
      parsed.patterns.push(...argv.slice(i + 1));
      break;
    }
    if (arg === "--help" || arg === "-h") {
      parsed.help = true;
      continue;
    }
    if (arg === "--version" || arg === "-v") {
      parsed.version = true;
      continue;
    }
    if (arg === "--quiet" || arg === "-q") {
      parsed.quiet = true;
      continue;
    }
    if (arg === "--verbose") {
      parsed.verbose = true;
      continue;
    }
    if (arg === "--no-color") {
      parsed.noColor = true;
      continue;
    }
    if (arg === "--ignore") {
      const next = argv[i + 1];
      if (next === undefined) {
        parsed.error = "--ignore requires a pattern argument";
        return parsed;
      }
      parsed.ignore.push(next);
      i += 1;
      continue;
    }
    if (arg.startsWith("--ignore=")) {
      parsed.ignore.push(arg.slice("--ignore=".length));
      continue;
    }
    if (arg.startsWith("-") && arg !== "-") {
      parsed.error = `unknown option: ${arg}`;
      return parsed;
    }
    parsed.patterns.push(arg);
  }

  return parsed;
}

export const HELP_TEXT = `Usage: verify-codelock [options] <pattern> [<pattern>...]

Verifies that every tscodegen-generated file matched by the supplied glob
patterns still has a valid codelock hash. Files that are not generated by
tscodegen (i.e. do not contain an \`@generated Codelock<<...>>\` or
\`@generated-editable Codelock<<...>>\` marker) are silently skipped.

Intended for use in CI and pre-commit hooks.

Arguments:
  <pattern>             One or more glob patterns or file paths, in the style
                        of eslint / prettier (e.g. \`src/**/*\`, \`./file.ts\`).
                        Directories are expanded to \`<dir>/**/*\`.

Options:
  --ignore <pattern>    Exclude files matching <pattern>. May be repeated.
  --quiet, -q           Suppress per-file output and the summary line.
  --verbose             Log the status of every file, including skipped ones.
  --no-color            Disable colored output.
  --help, -h            Print this help message and exit.
  --version, -v         Print the installed tscodegen version and exit.

Exit codes:
  0   All matched tscodegen-generated files have valid codelocks.
  1   One or more files were tampered with, matched no files, or could not be
      read.
  2   Invalid invocation (e.g. missing patterns, unknown option).
`;

/**
 * Entrypoint used by `bin/verify-codelock.js`.
 */
export function main(
  argv: readonly string[],
  options: {
    stdout?: NodeJS.WritableStream;
    stderr?: NodeJS.WritableStream;
    cwd?: string;
    version?: string;
  } = {},
): number {
  const stdout = options.stdout ?? process.stdout;
  const stderr = options.stderr ?? process.stderr;
  const parsed = parseArgs(argv);

  if (parsed.error) {
    stderr.write(`verify-codelock: ${parsed.error}\n\n${HELP_TEXT}`);
    return 2;
  }

  if (parsed.help) {
    stdout.write(HELP_TEXT);
    return 0;
  }

  if (parsed.version) {
    stdout.write(`${options.version ?? readPackageVersion()}\n`);
    return 0;
  }

  if (parsed.patterns.length === 0) {
    stderr.write(`verify-codelock: no patterns provided.\n\n${HELP_TEXT}`);
    return 2;
  }

  const result = run(parsed.patterns, {
    cwd: options.cwd,
    ignore: parsed.ignore,
    quiet: parsed.quiet,
    verbose: parsed.verbose,
    noColor: parsed.noColor,
    stdout,
    stderr,
  });
  return result.exitCode;
}

function readPackageVersion(): string {
  try {
    const pkgPath = path.resolve(__dirname, "..", "..", "package.json");
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8")) as {
      version?: string;
    };
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
}
